#!/bin/bash

# 定義顏色，讓介面看起來像現代化 CLI
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}==============================================${NC}"
echo -e "${BLUE}   🤖 Gemini Screenshot Auto-Renamer Setup    ${NC}"
echo -e "${BLUE}==============================================${NC}"
echo ""

# 1. 檢查並偵測 Gemini 指令位置
echo -e "${YELLOW}[1/4] 正在尋找 Gemini CLI...${NC}"
if command -v gemini &> /dev/null; then
    DETECTED_GEMINI=$(which gemini)
    echo -e "${GREEN}✓ 發現 Gemini 指令於: $DETECTED_GEMINI${NC}"
    GEMINI_CMD="$DETECTED_GEMINI"
else
    echo -e "${RED}✗ 找不到 'gemini' 指令。${NC}"
    read -p "請輸入 gemini 執行檔的絕對路徑 (例如 /opt/homebrew/bin/gemini): " USER_GEMINI
    GEMINI_CMD="$USER_GEMINI"
fi

echo ""

# 2. 智慧偵測 macOS 截圖路徑
echo -e "${YELLOW}[2/4] 正在偵測系統截圖資料夾...${NC}"
# 使用 macOS defaults 指令讀取真實設定
SYSTEM_SCREENSHOT_DIR=$(defaults read com.apple.screencapture location 2>/dev/null)

# 如果讀不到，預設為桌面
if [ -z "$SYSTEM_SCREENSHOT_DIR" ]; then
    SYSTEM_SCREENSHOT_DIR="$HOME/Desktop"
fi

# 擴展 ~ 為完整路徑
SYSTEM_SCREENSHOT_DIR="${SYSTEM_SCREENSHOT_DIR/#\~/$HOME}"

echo -e "偵測到的截圖路徑為: ${BLUE}$SYSTEM_SCREENSHOT_DIR${NC}"
read -p "是否要監控此資料夾? (y/n) [預設: y]: " CONFIRM_SS
CONFIRM_SS=${CONFIRM_SS:-y}

WATCH_DIRS=()
if [[ "$CONFIRM_SS" =~ ^[Yy]$ ]]; then
    WATCH_DIRS+=("$SYSTEM_SCREENSHOT_DIR")
fi

echo ""

# 3. 詢問額外資料夾 (例如 Blog)
echo -e "${YELLOW}[3/4] 設定額外監控資料夾${NC}"
echo "您是否還有其他資料夾需要 AI 自動改名？(例如 Blog 文章目錄)"
echo "如果不加，請直接按 Enter 跳過。"

while true; do
    read -p "請輸入路徑 (或按 Enter 結束): " EXTRA_DIR
    if [ -z "$EXTRA_DIR" ]; then
        break
    fi
    
    # 處理 ~ 符號
    EXTRA_DIR="${EXTRA_DIR/#\~/$HOME}"

    if [ -d "$EXTRA_DIR" ]; then
        WATCH_DIRS+=("$EXTRA_DIR")
        echo -e "${GREEN}✓ 已加入: $EXTRA_DIR${NC}"
    else
        echo -e "${RED}⚠️  路徑不存在，請重新確認。${NC}"
    fi
done

echo ""

# 4. 生成 .env 檔案
echo -e "${YELLOW}[4/4] 正在生成設定檔 (.env)...${NC}"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ENV_FILE="$SCRIPT_DIR/.env"
LOG_FILE="$SCRIPT_DIR/monitor.log"

# 構建 Watch Dirs 字串
DIRS_STRING=""
for dir in "${WATCH_DIRS[@]}"; do
    DIRS_STRING+="    \"$dir\""$வையை'
'
done

cat > "$ENV_FILE" <<EOF
# ==============================================
# AI Auto-Rename Screenshot - Configuration File
# Generated by setup.sh on $(date)
# ==============================================

# [Required] Directories to monitor
WATCH_DIRS=(
$DIRS_STRING)

# [Optional] Path to the 'gemini' executable
GEMINI_CMD="$GEMINI_CMD"

# [Optional] Log file path
LOG_FILE="$LOG_FILE"
EOF

echo -e "${GREEN}✅ 設定完成！已建立 .env 檔案。${NC}"
echo ""
echo -e "您現在可以執行以下指令來測試："
echo -e "${BLUE}./monitor_gemini.sh${NC}"
